name: apt-get_install_inn2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  apt-get_install_inn2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          hostname
          echo $HOSTNAME
          sudo touch /etc/news/inn.conf || true
          sudo mkdir /etc/news
          sudo touch /etc/news/inn.conf
          sudo echo "domain: localhost.localdomain" > /etc/news/inn.conf
          cat /etc/news/inn.conf
          sudo apt-get update -qq
          sudo apt-get install --yes inn2
          ls -Fla
      - run: |
          python3 --version
          echo "Node.js $(node --version)"
          nnptd --version || innd --version || inn2 --version || true
