name: apt-get_install_inn2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  apt-get_install_inn2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cat << EOF > inn.conf
            domain: localhost.localdomain
            mta: mta
            pathnews: pathnews
            hismethod: hismethod
            ovmethod: ovmethod
          EOF
          sudo mkdir /etc/news
          sudo mv inn.conf /etc/news/
          cat /etc/news/inn.conf
          sudo apt-get update -qq
          sudo apt-get install --yes inn2
      - run: |
          python3 --version
          echo "Node.js $(node --version)"
          nnptd --version || innd --version || inn2 --version || true
