name: InterNetNews2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  inn2:  # Almost always passes
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "localhost.localdomain" > hostname
          sudo mv hostname /etc/
          cat /etc/hostname
      - run: |
          sudo apt-get update -qq
          sudo apt-get install --yes inn2
      - run: cat /etc/news/inn.conf
      # innconfval: command not found
      # - run: |
      #    innconfval version
      #    innconfval hostname
      #    innconfval domain
      #    innconfval pathdb 
      - run: systemctl status inn2

  # nntplib_status:  # Passes
  #  needs: inn2
  #  runs-on: ubuntu-24.04
  #  steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12  # nntplib was removed from the Standard Library in Python 3.13.
      - name: nntplib_status
        shell: python
        run: |
          import nntplib  # Removed from the Standard Library in Python 3.13.
          # import ssl
          # ssl_context=ssl.create_default_context()
          # with nntplib.NNTP_SSL("localhost.localdomain", ssl_context=ssl_context) as nntp_server:  # Connection refused.
          # with nntplib.NNTP("localhost.localdomain", readermode=True) as nntp_server:  # Hangs.
          with nntplib.NNTP("localhost") as nntp_server:
              print(f"{nntp_server = }")
              # print(f"{nntp_server.starttls() = }")  # nntplib.NNTPTemporaryError: 401 MODE-READER
              print(f"{nntp_server.nntp_version = }")
              print(f"{nntp_server.nntp_implementation = }")
              print(f"{nntp_server.getwelcome() = }")
              print(f"{nntp_server.getcapabilities() = }")
              print(f"{nntp_server.list() = }")
              print("News group list:")
              print("\n".join(group_info.group for group_info in nntp_server.list()[1]))

  # nntplib_group:
  #  needs: inn2
  #  runs-on: ubuntu-24.04
  #  steps:
  #    - uses: actions/setup-python@v5
  #      with:
  #        python-version: 3.12  # nntplib was removed from the Standard Library in Python 3.13.
      - name: nntplib_group
        shell: python
        run: |
          import nntplib  # Removed from the Standard Library in Python 3.13.
          # import ssl
          # ssl_context=ssl.create_default_context()
          # with nntplib.NNTP_SSL("localhost.localdomain", ssl_context=ssl_context) as nntp_server:
          with nntplib.NNTP("localhost.localdomain", readermode=True) as nntp_server:
              resp, count, first, last, name = nntp_server.group('junk')
              print(f"Group '{name}' has {count} articles, range {first} to {last}.")

  # nntplib_newsgroups:
  #  needs: inn2
  #  runs-on: ubuntu-24.04
  #  steps:
  #    - uses: actions/setup-python@v5
  #      with:
  #        python-version: 3.12  # nntplib was removed from the Standard Library in Python 3.13.
      - name: nntplib_newsgroups
        shell: python
        run: |
          import nntplib  # Removed from the Standard Library in Python 3.13.
          from datetime import date, timedelta
          with nntplib.NNTP("localhost.localdomain", readermode=True) as nntp_server:
              resp, groups = nntp_server.newgroups(date.today() - timedelta(days=3))
              print(f"{resp = }, {len(groups) = }")

  # nntplib_post:
  #  needs: inn2
  #  runs-on: ubuntu-24.04
  #  steps:
  #    - uses: actions/setup-python@v5
  #      with:
  #        python-version: 3.12  # nntplib was removed from the Standard Library in Python 3.13.
      - name: nntplib_post
        shell: python
        run: |
          import nntplib  # Removed from the Standard Library in Python 3.13.
          import pathlib
          import time
          with nntplib.NNTP("localhost.localdomain", readermode=True) as nntp_server:
              msg = pathlib.Path("inn_article_001.txt").read_text()
              print(f"{msg = }")
              response = nntp_server.post(msg.encode("utf-8"))
              print(f"{response = }")
              resp, count, first, last, name = nntp_server.group('local.test')
              print(f"Group '{name}' has {count} articles, range {first} to {last}.")
              # time.sleep(5)
              # resp, count, first, last, name = nntp_server.group('local.test')
              # print(f"Group '{name}' has {count} articles, range {first} to {last}.")
              stat = nntp_server.stat()  # last() and next() both fail
              print(f"{stat = }")
              article = nntp_server.article(stat[2])
              print(f"{article = }")
              print("\n".join(line.decode("utf-8") for line in article[2].lines))

  # nntplib_overviews:
  #  needs: inn2
  #  runs-on: ubuntu-24.04
  #  steps:
  #    - uses: actions/setup-python@v5
  #      with:
  #        python-version: 3.12  # nntplib was removed from the Standard Library in Python 3.13.
      - name: nntplib_overviews
        shell: python
        run: |
          import nntplib  # Removed from the Standard Library in Python 3.13.
          with nntplib.NNTP("localhost.localdomain", readermode=True) as nntp_server:
              resp, count, first, last, name = nntp_server.group('junk')
              print(resp, count, first, last, name)
              resp, overviews = nntp_server.over((last - 9, last))
              for id, over in overviews:
                  print(id, nntplib.decode_header(over['subject']))
