name: InterNetNews2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  inn2:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]  # Running two instances of inn2 simultaneously fails.
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12  # nntplib was removed in Python 3.13
      - run: |
          echo "localhost.localdomain" > hostname
          sudo mv hostname /etc/
          cat /etc/hostname
      - run: |
          sudo apt-get update -qq
          sudo apt-get install --yes inn2
      - run: cat /etc/news/inn.conf
      - run: systemctl status inn2
      - shell: python
        run: |
          import nntplib  # Removed from the Standard Library in Python 3.13.
          import pathlib
          import ssl
          import textwrap
          import time
          # from email.message import EmailMessage
          # from nntplib import NNTP_SSL
          # ssl_context=ssl.create_default_context()
          # with nntplib.NNTP_SSL("localhost.localdomain", ssl_context=ssl_context) as nntp_server:  # Connection refused.
          # with nntplib.NNTP("localhost.localdomain", readermode=True) as nntp_server:  # Hangs.
          with nntplib.NNTP("localhost.localdomain") as nntp_server:
              print(f"{nntp_server = }")
              # print(f"{nntp_server.starttls() = }")  # nntplib.NNTPTemporaryError: 401 MODE-READER
              print(f"{nntp_server.nntp_version = }")
              print(f"{nntp_server.nntp_implementation = }")
              print(f"{nntp_server.getwelcome() = }")
              print(f"{nntp_server.getcapabilities() = }")
              print(f"{nntp_server.list() = }")
              print("\n".join(group_info.group for group_info in nntp_server.list()[1]))
              resp, count, first, last, name = nntp_server.group('junk')
              print('Group', name, 'has', count, 'articles, range', first, 'to', last)
              msg = pathlib.Path("inn_article_001.txt").read_text()
              print(f"{msg = }")
              # The commands below fail...
              response = nntp_server.post(msg)
              print(f"{response = }")
              # print(f"{nntp_server.group('local.test') = }")
              resp, count, first, last, name = nntp_server.group('local.test')
              print('Group', name, 'has', count, 'articles, range', first, 'to', last)
              from datetime import date, timedelta
              resp, groups = nntp_server.newgroups(date.today() - timedelta(days=3))
              print(f"{resp = }, {len(groups) = }")
              print(f"{resp[0] = }")
              resp, count, first, last, name = nntp_server.group('local.test')
              print('Group', name, 'has', count, 'articles, range', first, 'to', last)
              resp, overviews = nntp_server.over((last - 9, last))
              for id, over in overviews:
                  print(id, nntplib.decode_header(over['subject']))
