name: apt-get_install_inn2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  apt-get_install_inn2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "localhost.localdomain" > hostname
          sudo mv hostname /etc/
      - run: |
          sudo apt-get update -qq
          sudo apt-get install --yes inn2
      - run: cat /etc/news/inn.conf
      - run: |
          python3 --version
          echo "Node.js $(node --version)"
          nnptd --version || innd --version || inn2 --version || true
