name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update -qq
          sudo apt-get install --yes inn2
          ls -Fla
      - run: |
          python3 --version
          echo "Node.js $(node --version)"
          nnptd --version || innd --version || inn2 --version || true
